version: "2.1"

volumes:
  zm_events:
  zm_images:
  zm_mysql:
  zm_logs:

services:
  zoneminder:
    build: .
    privileged: true
    shm_size: 1G
    ports:
      - "80:80/tcp"
    volumes:
      - "zm_events:/var/cache/zoneminder/events"
      - "zm_images:/var/cache/zoneminder/images"
      - "zm_mysql:/var/lib/mysql"
      - "zm_logs:/var/log/zm"
