version: "2.1"

volumes:
  zm_events:
  zm_images:
  zm_tokens:
  db:

services:
  zm:
    build: zm
    privileged: true
    ports:
      - 80:80/tcp
      - 9000:9000/tcp
    volumes:
      - zm_events:/var/cache/zoneminder/events
      - zm_images:/var/cache/zoneminder/images
      - zm_tokens:/var/lib/zmeventnotification/push
    tmpfs:
      - /var/log
      - /var/cache/zoneminder/temp
      - /var/cache/zoneminder/cache
    shm_size: 2048M
    depends_on:
      - db

  # https://hub.docker.com/_/mariadb/
  db:
    build: db
    volumes:
      - db:/var/lib/mysql
  
  # https://hub.docker.com/_/mariadb/
  sqldump:
    build: db
    command: "/sqldump.sh"
    volumes:
      - db:/var/lib/mysql
    depends_on:
      - db
