version: "2.1"

volumes:
  zm_events:
  zm_images:
  mariadb:
  duplicati:

services:
  zoneminder:
    build: .
    privileged: true
    ports:
      - "80:80/tcp"
      - "9000:9000/tcp"
    volumes:
      - "zm_events:/var/cache/zoneminder/events"
      - "zm_images:/var/cache/zoneminder/images"
    environment:
      SHMEM: 50%
      ZM_DB_HOST: mariadb
      ZM_DB_NAME: zm
      ZM_DB_USER: zmuser
      ZM_DB_PASS: zmpass

  # https://hub.docker.com/_/mariadb/
  mariadb:
    image: mariadb:10.5
    volumes:
      - "mariadb:/var/lib/mysql"
  
  mysqldump:
    image: mariadb:10.5
    volumes:
      - "mariadb:/var/lib/mysql"
    command:
      - "/bin/bash"
      - "-c"
      - "while : ; sleep ${INTERVAL} ; do mysqldump -h mariadb -u root -p${MYSQL_ROOT_PASSWORD} -d zm > /var/lib/mysql/mysqldump.sql ; done"
    environment:
      INTERVAL: 14400

  # https://hub.docker.com/r/linuxserver/duplicati
  duplicati:
    image: linuxserver/duplicati:arm64v8-latest
    environment:
      PUID: "0"
      PGID: "0"
      CLI_ARGS: --webservice-interface=any
    ports:
      - 8201:8200/tcp
    volumes:
      - duplicati:/config
      - zm_events:/source/zm_events:ro
      - zm_images:/source/zm_images:ro
      - mariadb:/source/mariadb:ro
